### ISSUE TITLE
[CAT]Component Diagram

### ISSUE THREAD

**Issue by ahmetsenturk** [TUM-Dev/gocast_mobile#278]
- [x] Normal lines like components

- [ ] Fix animation with arrows

- [ ] getStream() made some confusion - change to getStreamURL/getmetadata ?

- [x] Get ride of previous step so that user can follow better the flow

- [x] The camera is not the ideal icon here(may be an eye)

**Comment by mo-cmyk** [comment]
see additional comments on the keynote (I rewatched the feedback video and noticed we missed some stuff above)

**Comment by cbetul** [comment]
> see additional comments on the keynote (I rewatched the feedback video and noticed we missed some stuff above)

`They didn’t; want the lollipop to be on the corner bur rather a continuous line and we should adjust the alignment `

I guess this is the comment, not sure I got it correctly, but did they ask to remove the lollipop icons completely and use a solid line instead?
If I understand correctly, I will update and align it now.

**Comment by mo-cmyk** [comment]
> > see additional comments on the keynote (I rewatched the feedback video and noticed we missed some stuff above)
> 
> `They didn’t want the lollipop to be on the corner bur rather a continuous line and we should adjust the alignment `
> 
> I guess this is the comment, not sure I got it correctly, but did they ask to remove the lollipop icons completely and use a solid line instead? If I understand correctly, I will update and align it now.

You guessed correctly this is one of the comments 👍

As far as understood it they are quite keen on the lollipops since they show the dataflow (especially in terms of providing and receiving data). But they mentioned that the line should be straight and not going around corners since this might be difficult for the viewer to grasp. 

This is an instance of the problem:

![Image](https://github.com/TUM-Dev/gocast_mobile/assets/58398080/c89b5f3d-fb9b-4e35-a3bf-9a5cf760cb46)

_TL:DR_
- Lollipops should stay
- Alignment of the boxes needs to be fixed
- Lines should be as straight es possible (avoiding corners if possible)

(Since @GravityDarkLab was kind enough to post the feedback and the recordings of the feedback on [Confluence](https://confluence.ase.in.tum.de/display/iOS2324TUM/Team+TUM%3A+CAT+Dry+Run+Preparation) you can also take a look at the summary and/or rewatch the feedback recording just to be sure everything is covered 😅)
